# coding=utf-8

from nltk.corpus import stopwords

shortcuts =[
    "jr",
    "mr",
    "mrs",
    "ms",
    "dr",
    "prof",
    "sr",
    "sen",
    "corp",
    "rep",
    "gov",
    "atty",
    "supt",
    "det",
    "rev",
    "col",
    "gen",
    "lt",
    "cmdr",
    "adm",
    "capt",
    "sgt",
    "cpl",
    "maj",
    "esq",
    "mstr",
    "phd",
    "adj",
    "adv",
    "asst",
    "bldg",
    "brig",
    "comdr",
    "hon",
    "messrs",
    "mlle",
    "mme",
    "op",
    "ord",
    "pvt",
    "reps",
    "res",
    "sens",
    "sfc",
    "surg",
    "pres",
    "sec",
    "supt",
    "pang",
    "engr",
    "dept",
    "mz",
    "mx",
    "br",
    "fr",
    "pr",
    "ave",
    "st",
    "brgy",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "jan",
    "feb",
    "mar",
    "apr",
    "jun",
    "jul",
    "aug",
    "sep",
    "sept",
    "oct",
    "nov",
    "dec",
    "comp", #computer
    "mt", #mountain
    "sta", #santa
    "ma" #maria
  ]

utf8seed = [
    ("ÃƒÂ±"     , "ñ"),
    ("Ãƒâ€˜"    , "Ñ" ),
    ("Ã¢â‚¬â„¢" , "\'"),
    ("ÃƒÂ¡"     , "á"),
    ("ÃƒÂ¤"     , "ä"),
    ("Ãƒâ€ž"    , "ä"),
    ("ÃƒÂ§"     , "ç"),
    ("ÃƒÂ©"     , "é"),
    ("Ãƒâ€°"    , "É"),
    ("ÃƒÂ¨"     , "è"),
    ("ÃƒÂ¬"     , "ě"),
    ("ÃƒÂª"     , "ê"),
    ("ÃƒÂ­"     , "í" ),
    ("ÃƒÂ¯"     , "ï"),
    ("Ã„Â©"     , "ĩ"),
    ("ÃƒÂ³"     , "ó"),
    ("ÃƒÂ¸"     , "ø"),
    ("ÃƒÂ¶"     , "ö"),
    ("Ãƒâ€“"    , "ö"),
    ("Ã…Â¡"     , "š"),
    ("ÃƒÂ¼"     , "ü"),
    ("LÃƒÂº"    , "ú"),
    ("Ã…Â©"     , "ũ"),
    ("Ã±"       , "ñ"),
    ("â‚¬"      , "€"),
    ("â€š"      , "‚"),
    ("Æ’"       , "ƒ"),
    ("â€ž"      , "„"),
    ("â€¦"      , "…"),
    ("â€"       , "†"),
    ("â€¡"      , "‡"),
    ("Ë†"       , "ˆ"),
    ("â€°"      , "‰"),
    ("Å"        , "Š"),
    ("â€¹"      , "‹"),
    ("Å’"       , "Œ"),
    ("Å½"       , "Ž"),
    ("â€˜"      , "\'"), #original : ‘
    ("â€™"      , "\'"), #original : ’
    ("â€œ"      , "\""), #orig : “
    ("â€"       , "\""), #orig : ”
    ("â€¢"      , "•"),
    ("â€“"      , "–"),
    ("â€”"      , "—"),
    ("Ëœ"       , "˜"),
    ("â„¢"      , "™"),
    ("Å¡"       , "š"),
    ("â€º"      , "›"),
    ("Å“"       , "œ"),
    ("Å¾"       , "ž"),
    ("Å¸"       , "Ÿ"),
    ("Â"        , " "),
    ("Â¡"       , "¡"),
    ("Â¢"       , "¢"),
    ("Â£"       , "£"),
    ("Â¤"       , "¤"),
    ("Â¥"       , "¥"),
    ("Â¦"       , "¦"),
    ("Â§"       , "§"),
    ("Â¨"       , "¨"),
    ("Â©"       , "©"),
    ("Âª"       , "ª"),
    ("Â«"       , "¬"),
    ("Â®"       , "®"),
    ("Â¯"       , "¯"),
    ("Â°"       , "°"),
    ("Â±"       , "±"),
    ("Â²"       , "²"),
    ("Â³"       , "³"),
    ("Â´"       , "\'"), #orig : ´
    ("Âµ"       , "µ"),
    ("Â¶"       , "¶"),
    ("Â·"       , "·"),
    ("Â¸"       , "¸"),
    ("Â¹"       , "¹"),
    ("Âº"       , "º"),
    ("Â»"       , "»"),
    ("Â¼"       , "¼"),
    ("Â½"       , "½"),
    ("Â¾"       , "¾"),
    ("Â¿"       , "¿"),
    ("Ã€"       , "À" ),
    ("Ã"        , "Á"  ),
    ("Ã‚"       , "Â" ),
    ("Ãƒ"       , "Ã" ),
    ("Ã„"       , "Ä" ),
    ("Ã…"       , "Å" ),
    ("Ã†"       , "Æ" ),
    ("Ã‡"       , "Ç" ),
    ("Ãˆ"       , "È" ),
    ("Ã‰"       , "É" ),
    ("ÃŠ"       , "Ê" ),
    ("Ã‹"       , "Ë" ),
    ("ÃŒ"       , "Ì" ),
    ("Ã"        , "Í"  ),
    ("ÃŽ"       , "Î" ),
    ("Ã"        , "Ï"  ),
    ("Ã"        , "Ð"  ),
    ("Á‘"       , "Ñ" ),
    ("Ã‘"       , "Ñ" ),
    ("Ã’"       , "Ò" ),
    ("Ã“"       , "Ó" ),
    ("Ã”"       , "Ô" ),
    ("Ã•"       , "Õ" ),
    ("Ã–"       , "Ö" ),
    ("Ã—"       , "×" ),
    ("Ã˜"       , "Ø" ),
    ("Ã™"       , "Ù" ),
    ("Ãš"       , "Ú" ),
    ("Ã›"       , "Û" ),
    ("Ãœ"       , "Ü" ),
    ("Ã"        , "Ý"  ),
    ("Ãž"       , "Þ" ),
    ("ÃŸ"       , "ß" ),
    ( "Ã"       , "à"  ),
    ("Ã¡"       , "á" ),
    ("Ã¢"       , "â" ),
    ("Ã£"       , "ã" ),
    ("Ã¤"       , "ä" ),
    ("Ã¥"       , "å" ),
    ("Ã¦"       , "æ" ),
    ("Ã§"       , "ç" ),
    ("Ã¨"       , "è" ),
    ("Ã©"       , "é" ),
    ("Ãª"       , "ê" ),
    ("Ã«"       , "ë" ),
    ("Ã¬"       , "ì" ),
    ( "Ã"       , "í" ),
    ("Ã®"       , "î" ),
    ("Ã¯"       , "ï" ),
    ("Ã°"       , "ð" ),
    ("Ã±"       , "ñ" ),
    ("Ã²"       , "ò" ),
    ("Ã³"       , "ó" ),
    ("Ã´"       , "ô" ),
    ("Ãµ"       , "õ" ),
    ("Ã¶"       , "ö" ),
    ("Ã·"       , "÷" ),
    ("Ã¸"       , "ø" ),
    ("Ã¹"       , "ù" ),
    ("Ãº"       , "ú" ),
    ("Ã»"       , "û" ),
    ("Ã¼"       , "ü" ),
    ("Ã½"       , "ý" ),
    ("Ã¾"       , "þ" ),
    ("Ã¿"       , "ÿ" ),
    ("“"        , "\""),
    ("”"        , "\""),
    ("‘"        , "\'"),
    ("’"        , "\'"),
    ("\n"       , " "),
    ("–"        , "-"),
    ("â€™"      , "\'"),
    ("†™"       , "\'"),
    ("``"       , "\""),
    ("`"        , "\'"),];

domains = [
    ".com",
    ".ph",
    ".net",
    ".jp",
    ".com.ph",
    ".net.ph",
    ".org",
    ".int",
    ".edu",
    ".edu.ph",
    ".gov",
    ".gov.ph",
    ".co",
    ".co.kr"
  ]

honorifics = [
    "Mr.",
    "Mrs.",
    "Ms.",
    "Sen.",
    "Dr.",
    "Prof.",
    "Usec",
    "Usec.",
    "Senator",
    "President",
    "Prime Minister",
    "Secretary",
    "Justice",
    "Mayor",
    "Pangulong",
    "Vice President",
    "Senadora"]

trashparts = [
    'DISCLAIMER: Sun.Star website welcomes friendly debate, but comments posted on this site do not necessary reflect the views of the Sun.Star management and its affiliates. Sun.Star reserves the right to delete, reproduce or modify comments posted here without notice. Posts that are inappropriate will automatically be deleted. Forum rules: Do not use obscenity. Some words have been banned. Stick to the topic. Do not veer away from the discussion. Be coherent and respectful. Do not shout or use CAPITAL LETTERS!  Please enable JavaScript to view the comments powered by Disqus.',
    'Share this:Share on Facebook (Opens in new window)Click to share on Twitter (Opens in new window)Click to share on Google+ (Opens in new window)Click to share on Tumblr (Opens in new window)Click to share on Reddit (Opens in new window)Click to email this to a friend (Opens in new window)Click to print (Opens in new window)MoreClick to share on Pinterest (Opens in new window)Click to share on LinkedIn (Opens in new window)  Related  comments',
    'InterAksyon.com The online news portal of TV5 MANILA',
    'Business ( Article MRec ), pagematch: 1, sectionmatch: 1',
    'Headlines ( Article MRec ), pagematch: 1, sectionmatch: 1',
    'Article MRec',
    'pagematch: 1, sectionmatch: 1'
    ]

contraction_shortcuts = {
    "Jan.": "January",
    "Feb.": "February",
    "Mar.": "March",
    "Apr.": "April",
    "Jun.": "June",
    "Jul.": "July",
    "Aug.": "August",
    "Sep.": "September",
    "Sept.": "September",
    "Oct.": "October",
    "Nov.": "November",
    "Dec.": "December",
    "Mon.": "Monday",
    "Tue.": "Tuesday",
    "Wed.": "Wednesday",
    "Thu.": "Thursday",
    "Fri.": "Friday",

    "ain't": "am not", #are not; is not; has not; have not
    "aren't": "are not", #am not
    "can't": "cannot",
    "can't've": "cannot have",
    "'cause": "because",
    "could've": "could have",
    "couldn't": "could not",
    "couldn't've": "could not have",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hadn't've": "had not have",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he had", #he would
    "he'd've": "he would have",
    "he'll": "he shall", #he will
    "he'll've": "he shall have", #he will have
    "he's": "he has", #he is
    "how'd": "how did",
    "how'd'y": "how do you",
    "how'll": "how will",
    "how's": "how has", #how is | how does
    "I'd": "I had", #I would
    "I'd've": "I would have",
    "I'll": "I shall", #I will
    "I'll've": "I shall have", #I will have
    "I'm": "I am",
    "I've": "I have",
    "isn't": "is not",
    "it'd": "it had", #it would
    "it'd've": "it would have",
    "it'll": "it shall", #it will
    "it'll've": "it shall have", #it will have
    "it's": "it has", #it is
    "let's": "let us",
    "ma'am": "madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "must've": "must have",
    "mustn't": "must not",
    "mustn't've": "must not have",
    "needn't": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "oughtn't": "ought not",
    "oughtn't've": "ought not have",
    "shan't": "shall not",
    "sha'n't": "shall not",
    "shan't've": "shall not have",
    "she'd": "she had", #she would
    "she'd've": "she would have",
    "she'll": "she shall", #she will
    "she'll've": "she shall have", #she will have
    "she's": "she has", #she is
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "so's": "so as", #so is
    "that'd": "that would", #that had
    "that'd've": "that would have",
    "that's": "that has", #that is
    "there'd": "there had", #there would
    "there'd've": "there would have",
    "there's": "there has", #there is
    "they'd": "they had", #they would
    "they'd've": "they would have",
    "they'll": "they shall", #they will
    "they'll've": "they shall have", #they will have
    "they're": "they are",
    "they've": "they have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd": "we had", #we would
    "we'd've": "we would have",
    "we'll": "we will",
    "we'll've": "we will have",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what shall", #what will
    "what'll've": "what shall have", #what will have
    "what're": "what are",
    "what's": "what has", #what is
    "what've": "what have",
    "when's": "when has", #when is
    "when've": "when have",
    "where'd": "where did",
    "where's": "where has", #where is
    "where've": "where have",
    "who'll": "who shall", #who will
    "who'll've": "who shall have", #who will have
    "who's": "who has", #who is
    "who've": "who have",
    "why's": "why has", #why is
    "why've": "why have",
    "will've": "will have",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't": "would not",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you had", #you would
    "you'd've": "you would have",
    "you'll": "you shall", #you will
    "you'll've": "you shall have", #you will have
    "you're": "you are",
    "you've": "you have",
    "gov't" : "government",
    "Pres." : "President"
}

def getStopwords(language):
    if language == 'english':
        words = stopwords.words('english')
        weekdays = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']
        added = ['far','growth','approach','expressed','many','aside','department','sa','once','despite','however', 'also', 'since', 'si', 'ko', 'ang', 'ho', 'alam', 'ako', 'disprove', 'girl', 'use', 'oh', 'instead', "jr", "show", "till"]
        #extra_chars = ['``', '\'\'', '\"\"','\'', '\"', '’', '”', '‘']
        words.extend(weekdays)
        #words.extend(extra_chars)
        words.extend(added)
        return words
    else:
        words = stopwords.words(language)
        return words

extra_symbols = ['``', '\'\'', '\"\"','\'', '\"', '?', '!', ',', ';', '(', ')', '.', '-', '@', ':', '[', ']', '|', "/", "\/"]

# contractions = [
#  ("I'm", "I am"),
#  ("I'd", "I had"),
#  ("I've", "I have"),
#  ("I'll", "I will"),
#  ("I'd", "I would")
# ]

languages = {
"af" : "Afrikaans",
"ar" : "Arabic",
"bg" : "Bulgarian",
"bn" : "Bengali",
"cs" : "Czech",
"da" : "Danish",
"de" : "German",
"el" : "Greek",
"en" : "English",
"es" : "Spanish",
"fa" : "Persian",
"fi" : "Finnish",
"fr" : "French",
"gu" : "Gujarati",
"he" : "Hebrew",
"hi" : "Hindi",
"hr" : "Croatian",
"hu" : "Hungarian",
"id" : "Indonesian",
"ja" : "Japanese",
"kn" : "Kannada",
"ko" : "Korean",
"lt" : "Lithuanian",
"lv" : "Latvian",
"ml" : "Malayalam",
"mr" : "Marathi",
"ne" : "Nepali",
"nl" : "Dutch",
"no" : "Norwegian",
"pa" : "Punjabi",
"pl" : "Polish",
"pt" : "Portuguese",
"ro" : "Romanian",
"ru" : "Russian",
"sk" : "Slovak",
"sl" : "Slovene",
"so" : "Somali",
"sq" : "Albanian",
"sv" : "Swedish",
"sw" : "Swahili",
"ta" : "Tamil",
"te" : "Telugu",
"th" : "Thai",
"tl" : "Tagalog",
"tr" : "Turkish",
"uk" : "Ukrainian",
"ur" : "Urdu",
"vi" : "Vietnamese",
"zh-cn" : " Simplified Chinese",
"zh-tw" : " Traditional Chinese"
}